spring.application.name=back

server.port=5000
spring.datasource.url=jdbc:sqlite:file:/home/gaspard/Documents/Projets/GillesdeChasles/data/gillesdechasles.db?mode=rwc
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false

jwt.secret=un_jwt_secret_long_comme_le_bras_mais_genre_vraiment_tres_long_pour_que_ce_soit_secure
jwt.expiration=3600000
app.cors.allowed-origin=http://localhost:4200
app.cookie.secure=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin