services:
  init-data:
    image: busybox
    user: root
    command: chown -R 100:101 /data
    volumes:
      - sqlite_data:/data

  backend:
    container_name: gillesdechasles-backend
    image: ghcr.io/gaspachoo/gillesdechasles-back:${TAG}
    env_file: /mnt/MainPool/GillesdeChasles/env/.env
    ports:
      - "5000:5000"
    networks:
      - gilles-de-chasles-network
    volumes:
      - sqlite_data:/data
    restart: unless-stopped

  frontend:
    container_name: gillesdechasles-frontend
    image: ghcr.io/gaspachoo/gillesdechasles-front:${TAG}
    env_file: /mnt/MainPool/GillesdeChasles/env/.env
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - gilles-de-chasles-network
    restart: unless-stopped


volumes:
  sqlite_data:

networks:
  gilles-de-chasles-network:
    driver: bridge
