services:
  backend:
    image: ghcr.io/gaspachoo/gillesdechasles-back:latest
    environment:
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JAVA_TOOL_OPTIONS: "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0"
    ports:
      - ${API_PORT}:8080
    networks:
      - gilles-de-chasles-network
    restart: unless-stopped

  frontend:
    image: ghcr.io/gaspachoo/gillesdechasles-front:latest
    environment:
      API_URL: ${API_URL}
    ports:
      - "${CLIENT_PORT}:4200"
    depends_on:
      - backend
    networks:
      - gilles-de-chasles-network
    restart: unless-stopped


volumes:
  sqlite_data:

networks:
  gilles-de-chasles-network:
    driver: bridge
